Suffer Travels/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Suffer_Travels.Data;
using Suffer_Travels.Models;
using Suffer_Travels.ViewModel;
using System.Net;
using System.Net.Mail;

namespace Suffer_Travels.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IWebHostEnvironment env;
        public AdminController(ApplicationDbContext _db, IWebHostEnvironment _env)
        {
            db = _db;
            env = _env;
        }

        public IActionResult AddCities()
        {
            if (UserLoggedOut())
                return RedirectToAction("Login", "User");

            if (!IsAdminUser())
                return RedirectToAction("Home", "User");

            TourViewModel tourViewModel = new TourViewModel();

            tourViewModel.cities = db.tblCity;
            tourViewModel.states = db.tblState;
            tourViewModel.countries = db.tblCountry;

            SetViewData();

            return View(tourViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCityDetailsAsync(TourViewModel tourViewModel)
        {
            if (UserLoggedOut())
                return RedirectToAction("Login", "User");

            if (!IsAdminUser())
                return RedirectToAction("Home", "User");

            var files = HttpContext.Request.Form.Files;
            foreach (var Image in files)
            {
                string[] Images = Image.FileName.Split(".");
                string extension = Images[Images.Length - 1].ToLower();
                if (extension != "jpg" && extension != "png")
                {
                    TempData["Error"] = "Only jpg and png files are allowed";
                    return RedirectToAction("AddCities");
                }
                if (Image != null && Image.Length > 0)
                {
                    var file = Image;
                    var uploads = Path.Combine(env.WebRootPath, "photos\\city");
                    if (file.Length > 0)
                    {
                        var fileName = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(file.FileName);
                        using (var fileStream = new FileStream(Path.Combine(uploads, fileName), FileMode.Create))
                        {
                            await file.CopyToAsync(fileStream);
                            tourViewModel.city.Photo = fileName;
                        }
                    }
                }
            }

            db.tblCity.Add(tourViewModel.city);
            db.SaveChanges();

            TempData["success"] = "Cities Added Successfully";

            return RedirectToAction("AddCities");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTourDetailsAsync(TourViewModel tourViewModel)
        {
            var files = HttpContext.Request.Form.Files;

            Photo _photos = new Photo();

            foreach (var Image in files)
            {
                string[] Images = Image.FileName.Split(".");
                string extension = Images[Images.Length - 1].ToLower();
                if (extension != "jpg" && extension != "png")
                {
                    TempData["Error"] = "Only jpg and png files are allowed";
                    return RedirectToAction("ManageTours");
                }
                if (Image != null && Image.Length > 0)
                {
                    var file = Image;
                    var uploads = Path.Combine(env.WebRootPath, "photos\\tour");
                    if (file.Length > 0)
                    {
                        var fileName = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(file.FileName);
                        using (var fileStream = new FileStream(Path.Combine(uploads, fileName), FileMode.Create))
                        {
                            await file.CopyToAsync(fileStream);
                            _photos.ImagePath = fileName;
                        }
                    }
                }
            }

            //db.tblTourType.Add(tourViewModel.tourTypeDetails);

            string description = tourViewModel.tourDetail.TourName;

            if (tourViewModel.tourDetail.TourTypeId == 0)
            {
                db.tblTourType.Add(tourViewModel.tourTypeDetails);
                db.SaveChanges();
                tourViewModel.tourDetail.TourTypeId = db.tblTourType.FirstOrDefault(t => t.TtName == tourViewModel.tourTypeDetails.TtName).TtId;
            }
            db.tblTour.Add(tourViewModel.tourDetail);

            _photos.Description = description;

            db.tblPhotos.Add(_photos);
            db.SaveChanges();

            TourPhotos _tourPhotos = new TourPhotos();
            _tourPhotos.TourId = db.tblTour.FirstOrDefault(t => t.TourName == tourViewModel.tourDetail.TourName).TId;
            _tourPhotos.PhotoId = db.tblPhotos.FirstOrDefault(p => p.ImagePath == _photos.ImagePath).PId;
            db.tblTourPhotos.Add(_tourPhotos);

            TourDates tourDates = new TourDates();
            DateTime sixMonths = tourViewModel.tourDate.Date.AddMonths(6);
            List<TourDates> td = new List<TourDates>();
            switch (tourViewModel.recurrence)
            {
                case ("Day"):
                    while (tourViewModel.tourDate.Date < sixMonths)
                    {
                        td.Add(new TourDates { Date = tourViewModel.tourDate.Date, Time = DateTime.Now, TourId = _tourPhotos.TourId });

                        tourViewModel.tourDate.Date = tourViewModel.tourDate.Date.AddDays(tourViewModel.repeatsEvery);
                    }
                    break;

                case ("Week"):
                    while (tourViewModel.tourDate.Date < sixMonths)
                    {
                        td.Add(new TourDates { Date = tourViewModel.tourDate.Date, Time = DateTime.Now, TourId = _tourPhotos.TourId });

                        tourViewModel.tourDate.Date = tourViewModel.tourDate.Date.AddDays(tourViewModel.repeatsEvery * 7);
                    }
                    break;

                case ("Month"):
                    while (tourViewModel.tourDate.Date < sixMonths)
                    {
                        td.Add(new TourDates { Date = tourViewModel.tourDate.Date, Time = DateTime.Now, TourId = _tourPhotos.TourId });

                        tourViewModel.tourDate.Date = tourViewModel.tourDate.Date.AddMonths((int)tourViewModel.repeatsEvery);
                    }
                    break;

                case ("Year"):
                    while (tourViewModel.tourDate.Date < sixMonths.AddYears(6))
                    {
                        td.Add(new TourDates { Date = tourViewModel.tourDate.Date, Time = DateTime.Now, TourId = _tourPhotos.TourId });

                        tourViewModel.tourDate.Date = tourViewModel.tourDate.Date.AddYears((int)tourViewModel.repeatsEvery);
                    }
                    break;

                default:
                    break;
            }

            db.tblTourDates.AddRange(td);
            db.SaveChanges();

            TempData["Success"] = "Data added successfully";

            return RedirectToAction("ManageTours");
        }

        public IActionResult AddTourItineary(uint? id)
        {
            TourViewModel tourViewModel;
            if (UserLoggedOut())
                return RedirectToAction("Login", "User");

            if (!IsAdminUser())
                return RedirectToAction("Home", "User");

            SetViewData();

            if (id == null || id == 0)
            {
                TempData["Error"] = "No matching results found";
                return RedirectToAction("ViewUsers");
            }

            tourViewModel = new TourViewModel();
            tourViewModel.tourDetail = db.tblTour.First(t => t.TId == id);
            tourViewModel.NoOfDays = Convert.ToInt32(tourViewModel.tourDetail.NoOfDays);
            tourViewModel.TourId = id;

            tourViewModel.cities = db.tblCity;
            tourViewModel.countries = db.tblCountry;
            tourViewModel.states = db.tblState;
            tourViewModel.landmarks = db.tblLandMark;

            //tourViewModel.tourDetail = db.tblTour.Find(id);

            return View(tourViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddTourItineary([FromRoute]uint? id, TourViewModel tourViewModel)
        {
            List<TourItinerary> tiList = new List<TourItinerary>();
            IEnumerable<TourItinerary> tourItineraries = tourViewModel.tiList;
            
            if(id == null || id == 0)
            {
                TempData["Error"] = "No matching results found";
                return RedirectToAction("AddTourItineary");
            }
            int day = 1;
            foreach(var item in tourItineraries)
            {
                tiList.Add(new TourItinerary
                {
                    TourId = Convert.ToUInt32(id),
                    Day = Convert.ToUInt32(day),
                    CityId = Convert.ToUInt32(item.CityId),
                    Description = item.Description
                });
                day++;
            }

            db.tblTourItinerary.AddRange(tiList);
            db.SaveChanges();

            return RedirectToAction("ManageTours");
        }

        public IActionResult ApproveRole(uint? id)
        {
            if (id == null || id == 0)
            {
                TempData["Error"] = "No matching results found";
                return RedirectToAction("ViewUsers");
            }
            var _user = db.tblUser.Find(id);
            _user.Status = ApproveStatus();
            _user.ChangedAt = DateTime.Today;
            db.tblUser.Update(_user);
            db.SaveChanges();

Suffer Travels/Controllers/HotelController.cs
using Microsoft.AspNetCore.Mvc;
using Suffer_Travels.Data;
using Suffer_Travels.Models;
using Suffer_Travels.ViewModel;

namespace Suffer_Travels.Controllers
{
    public class HotelController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IWebHostEnvironment env;
        public HotelController(ApplicationDbContext _db, IWebHostEnvironment _env)
        {
            db = _db;
            env = _env;
        }

        public IActionResult Home()
        {
            /*String email = HttpContext.Session.GetString("Email").ToString();
            ViewData["ApprovalFlag"] = db.tblUser.First(user => user.Email == email).Status;*/
            SetViewData();
            return View();
        }

        [NonAction]
        public bool IsHotelUser()
        {
            return HttpContext.Session.GetInt32("RoleId") == 3;
        }        

        
        public IActionResult RegisterHotel()
        {
            if (UserLoggedOut())
                return RedirectToAction("Login", "User");

            if (IsHotelUser())
            {
                HotelViewModel hotelViewModel = new HotelViewModel();
                hotelViewModel.cities = db.tblCity;
                SetViewData();
                return View(hotelViewModel);                
            }

            return RedirectToAction("Home", "User");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterHotelAsync(HotelViewModel hotelViewModel)
        {
            if (UserLoggedOut())
                return RedirectToAction("Login", "User");

            if (!IsHotelUser())
                return RedirectToAction("Home", "User");

            SetViewData();

            string filen = "";

            Hotel hotel = new Hotel();
            hotel.HName = hotelViewModel.hotel.HName;
            hotel.HotelType = hotelViewModel.hotel.HotelType;
            hotel.ContactNo = hotelViewModel.hotel.ContactNo;
            hotel.AreaId = hotelViewModel.hotelAddress.CityId;

            HotelAddress hotelAddress = new HotelAddress();
            hotelAddress.AddressLine1 = hotelViewModel.hotelAddress.AddressLine1;
            hotelAddress.AddressLine2 = hotelViewModel.hotelAddress.AddressLine2;
            hotelAddress.CityId = hotelViewModel.hotelAddress.CityId;            

            var dbTrans = db.Database.BeginTransaction();
            try
            {
                db.tblHotelMaster.Add(hotel);
                db.SaveChanges();
                db.tblHotelAddress.Add(hotelAddress);
                db.SaveChanges();

                Photo photo = new Photo();

                var files = HttpContext.Request.Form.Files;

                foreach (var Image in files)
                {
                    string[] Images = Image.FileName.Split(".");
                    string extension = Images[Images.Length - 1].ToLower();
                    if (extension != "jpg" && extension != "png")
                    {
                        ModelState.AddModelError("photo.ImagePath", "Only jpg and png image formates are supported!");
                        return View(hotelViewModel);
                    }
                    if (Image != null && Image.Length > 0)
                    {
                        var file = Image;

                        var uploads = Path.Combine(env.WebRootPath, "photos\\hotel");
                        if (file.Length > 0)
                        {
                            var fileName = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(file.FileName);
                            using (var fileStream = new FileStream(Path.Combine(uploads, fileName), FileMode.Create))
                            {
                                await file.CopyToAsync(fileStream);
                                photo.ImagePath = fileName;
                                photo.Description = hotel.HName;
                                filen = fileName;
                                db.tblPhotos.Add(photo);
                                db.SaveChanges();

                            }
                        }
                    }
                }

                HotelPhotos hotelPhotos = new HotelPhotos();
                hotelPhotos.HId = db.tblHotelMaster.FirstOrDefault(h => h.HName == hotelViewModel.hotel.HName).HId;
                hotelPhotos.PID = db.tblPhotos.FirstOrDefault(p => p.ImagePath == filen).PId;
                db.tblHotelPhotos.Add(hotelPhotos);
                db.SaveChanges();

                /*HotelRooms hotelRooms = new HotelRooms();
                hotelRooms.TotalRooms = 100;
                hotelRooms.HId = db.tblHotelMaster.FirstOrDefault(h => h.HName == hotelViewModel.hotel.HName).HId;*/
                for(int i=0; i<5; ++i)
                {   
                    if(hotelViewModel.hrList[i].TotalRooms == 0)
                    {
                        continue;
                    }

                    HotelRooms hotelRooms = new HotelRooms();
                    hotelRooms.TotalRooms = hotelViewModel.hrList[i].TotalRooms;
                    hotelRooms.HId = db.tblHotelMaster.FirstOrDefault(h => h.HName == hotelViewModel.hotel.HName).HId;
                    hotelRooms.Price = hotelViewModel.hrList[i].Price;
                    hotelRooms.Capacity = hotelViewModel.hrList[i].Capacity;
                    db.tblHotelRooms.Add(hotelRooms);
                    db.SaveChanges();

                }
                //db.SaveChanges();
                dbTrans.Commit();

                TempData["success"] = "Details added successfully";
                return RedirectToAction("Home");
            }
            catch (Exception ex)
            {
                dbTrans.Rollback();
                TempData["Error"] = "Error";
                return RedirectToAction("Home");
            }

        }

        [NonAction]
        public void SetViewData()
        {
            ViewData["Fname"] = HttpContext.Session.GetString("Fname");
            ViewData["ProfilePhoto"] = HttpContext.Session.GetString("ProfilePhoto");
            String email = HttpContext.Session.GetString("Email").ToString();
            ViewData["ApprovalFlag"] = db.tblUser.First(user => user.Email == email).Status;
        }

        [NonAction]
        public bool UserLoggedOut()
        {

            return string.IsNullOrEmpty(HttpContext.Session.GetString("Email"));
        }
    }
}

Suffer Travels/Controllers/VehicleController.cs
using Microsoft.AspNetCore.Mvc;
using Suffer_Travels.Data;

namespace Suffer_Travels.Controllers
{
    public class VehicleController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IWebHostEnvironment env;
        public VehicleController(ApplicationDbContext _db, IWebHostEnvironment _env)
        {
            db = _db;
            env = _env;
        }

        public bool UserLoggedOut()
        {

            return string.IsNullOrEmpty(HttpContext.Session.GetString("Email"));
        }

        public bool IsVehicleUser()
        {
            return HttpContext.Session.GetInt32("RoleId") == 4;
        }

        public IActionResult Home()
        {
            if (UserLoggedOut())
                return RedirectToAction("Login", "User");

            if (!IsVehicleUser())
                return RedirectToAction("Home", "User");

            SetViewData();
            return View();
        }

        public void SetViewData()
        {
            ViewData["Fname"] = HttpContext.Session.GetString("Fname");
            ViewData["ProfilePhoto"] = HttpContext.Session.GetString("ProfilePhoto");
        }
    }
}

Suffer Travels/Views/Shared/User/_Admin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Safar Travels</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/theme4.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Suffer_Travels.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" />
    <link rel="icon" href="~/travel.png" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-dark bg-primary border-bottom box-shadow py-3 py-lg-3">
            <div class="container container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Home">Safar Travels</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="Home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="ViewUsers">Approve Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="ManageTours">Manage Tours</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="AddCities">Manage Cities</a>
                        </li>
                    </ul>
                    <span class="nav-item ml-auto">
                        <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="EditProfile">Hello, @ViewData["Fname"] <span class="small"><img src="/photos/user/@ViewData["ProfilePhoto"]" style="width: 1.3rem; height: 1.3rem; border-radius: 50%" /></span></a>
                    </span>
                    <span class="nav-item ml-auto">
                            <a class="nav-link text-white bg-danger" asp-area="" asp-controller="User" asp-action="Logout">Log out</a>
                    </span>
                </div>
            </div>
        </nav>
    </header>
    
    @RenderBody()
    
    <footer class="border-top footer text-muted">
        <div class="container">
            <partial name="_Notification" />
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Suffer Travels/Views/Shared/User/_Hotel.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Safar Travels</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/theme4.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Suffer_Travels.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" />
    <link rel="icon" href="~/travel.png" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-dark bg-primary border-bottom box-shadow py-3 py-lg-3">
            <div class="container container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Home">Safar Travels</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Hotel" asp-action="Home">Home</a>
                        </li>
                        @if (ViewData.ContainsKey("ApprovalFlag"))
                        {
                            if (ViewData["ApprovalFlag"].ToString() == "Approved")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Hotel" asp-action="RegisterHotel">Register Hotel</a>
                                </li>   
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Hotel" asp-action="RegisterHotel">Request for approval</a>
                                </li>
                            }
                        }
                    </ul>
                    <span class="nav-item ml-auto">
                        <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="EditProfile">Hello, @ViewData["Fname"] <span class="small"><img src="../photos/user/@ViewData["ProfilePhoto"]" style="width: 1.3rem; height: 1.3rem; border-radius: 50%" /></span></a>
                    </span>
                    <span class="nav-item ml-auto">
                            <a class="nav-link text-white bg-danger" asp-area="" asp-controller="User" asp-action="Logout">Log out</a>
                    </span>
                </div>
            </div>
        </nav>
    </header>
    
    @RenderBody()
    
    <footer class="border-top footer text-muted">
        <div class="container">
                    <partial name="_Notification" />
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $(document).ready( function () {
            $('#myTable').DataTable();
        } );
    </script>
    <script>
        
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Suffer Travels/Views/Shared/User/_Vehicle.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Suffer Travels</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/theme4.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Suffer_Travels.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" />
    <link rel="icon" href="~/travel.png" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-dark bg-primary border-bottom box-shadow py-3 py-lg-3">
            <div class="container container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="HomePage">Suffer Travels</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Vehicle" asp-action="Home">Home</a>
                        </li>
                        
                    </ul>
                    <span class="nav-item ml-auto">
                        <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="EditProfile">Hello, @ViewData["Fname"] <span class="small"><img src="../photos/user/@ViewData["ProfilePhoto"]" style="width: 1.3rem; height: 1.3rem; border-radius: 50%" /></span></a>
                    </span>
                    <span class="nav-item ml-auto">
                            <a class="nav-link text-white bg-danger" asp-area="" asp-controller="User" asp-action="Logout">Log out</a>
                    </span>
                </div>
            </div>
        </nav>
    </header>
    
    @RenderBody()
    
    <footer class="border-top footer text-muted">
        <div class="container">
                    <partial name="_Notification" />
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $(document).ready( function () {
            $('#myTable').DataTable();
        } );
    </script>
    <script>
        
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>