Suffer Travels/Controllers/ChartController.cs
using Microsoft.AspNetCore.Mvc;
using Suffer_Travels.Data;
using Suffer_Travels.Models;

namespace Suffer_Travels.Controllers
{
    public class ChartController : Controller
    {
        private readonly ApplicationDbContext db;
        public ChartController(ApplicationDbContext _db)
        {
            db = _db;
        }

        public IActionResult Index()
        {
            IEnumerable<User> user = db.tblUser;
            
            ViewData["User"] = user;
            return View(user);
        }
    }
}

Suffer Travels/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Suffer_Travels.Data;
using Suffer_Travels.Models;
using Suffer_Travels.ViewModel;
using System.Collections;
using System.Dynamic;
using System.Net;
using System.Net.Mail;

namespace Suffer_Travels.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IWebHostEnvironment env;
        private static int otp;
        public UserController(ApplicationDbContext _db, IWebHostEnvironment _env)
        {
            db = _db;
            env = _env;
        }

        public IActionResult Index()
        {
            string email;
            if ((email = UserCookieSet()) != null)
            {
                HttpContext.Session.SetString("Email", email);
            }
            return View();
        }

        public void SetSessionValues(string _email)
        {
            User user;
            int roleId;
            uint userId;
            string email = _email, fname, profilePhoto;

            user = db.tblUser.First(user => user.Email == email);

            userId = user.UId;
            roleId = Convert.ToInt32(user.RoleId);
            fname = user.Fname;
            profilePhoto = user.ProfilePhoto;

            HttpContext.Session.SetInt32("RoleId", roleId);
            HttpContext.Session.SetString("UserId", userId.ToString());
            HttpContext.Session.SetString("Email", email);
            HttpContext.Session.SetString("Fname", fname);
            HttpContext.Session.SetString("ProfilePhoto", profilePhoto);
        }

        public bool UserLoggedOut()
        {
            return string.IsNullOrEmpty(HttpContext.Session.GetString("Email"));
        }

        public bool ValidRole(int roleId)
        {
            return HttpContext.Session.GetInt32("RoleId") == roleId;
        }

        public Int32? GetRole()
        {
            return Convert.ToBoolean(HttpContext.Session.GetInt32("RoleId")) ? 
                HttpContext.Session.GetInt32("RoleId") : 0;
        }

        public string UserCookieSet()
        {
            if(HttpContext.Request.Cookies.Any(ck => ck.Key == "Email"))
            {
                return HttpContext.Request.Cookies.FirstOrDefault(ck => ck.Key == "Email").Value.ToString();
            }
            return null;

        }

        public IActionResult Home()
        {
            if (UserLoggedOut())
                return RedirectToAction("Login");

            SetSessionValues(HttpContext.Session.GetString("Email").ToString());

            if (GetRole() == 2)
            {
                TourViewModel tourViewModel = new TourViewModel();
                
                ViewData["Fname"] = HttpContext.Session.GetString("Fname");
                ViewData["ProfilePhoto"] = HttpContext.Session.GetString("ProfilePhoto");

                tourViewModel.tourDetails = db.tblTour;
                tourViewModel.tourTypes = db.tblTourType;
                tourViewModel.tourDates = db.tblTourDates;
                tourViewModel.tourPhotos = db.tblTourPhotos;
                tourViewModel.photos = db.tblPhotos;
                tourViewModel.favouriteTours = db.tblFavouriteTours;
                ViewData["UId"] = Convert.ToUInt32(HttpContext.Session.GetString("UserId"));

                return View(tourViewModel);
            }

            return ShowCustomHomePage(GetRole());
        }
        
        public IActionResult Login()
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("Email")))
                return RedirectToAction("Home");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(Register register)
        {
            IEnumerable<User> _user = db.tblUser;

            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("Email")))
                return RedirectToAction("Home");

            if (_user.Any(u => u.Email == register.Email && u.Password == register.Password))
            {
                User? user = _user.FirstOrDefault(u => u.Email == register.Email);

                if (string.IsNullOrEmpty(HttpContext.Session.GetString("Email")))
                {
                    // Setting Sessions
                    SetSessionValues(register.Email.ToString().Trim());

                    //HttpContext.Session.SetInt32("RoleId", Convert.ToInt32(user.RoleId));
                    //HttpContext.Session.SetString("Email", register.Email.ToString().Trim());
                    //HttpContext.Session.SetString("Fname", user.Fname.ToString().Trim());
                    //HttpContext.Session.SetString("ProfilePhoto", user.ProfilePhoto.ToString().Trim());
                }

                if (register.RememberMe)
                {
                    CookieOptions cookieOption = new CookieOptions();
                    cookieOption.Expires = new DateTimeOffset(DateTime.Now.AddDays(2));
                    HttpContext.Response.Cookies.Append(
                        "Email",
                        register.Email.ToString(),
                        cookieOption
                    );
                }

                return ShowCustomHomePage(HttpContext.Session.GetInt32("RoleId"));
            }

            return View(register);
        }

        public IActionResult ShowCustomHomePage(int? RoleId)
        {
            switch (RoleId)
            {
                case 1:
                    return RedirectToAction("Home", "Admin");

                case 2:
                    return RedirectToAction("Home");

                case 3:
                    return RedirectToAction("Home", "Hotel");

                case 4:
                    return RedirectToAction("Home", "Vehicle");

                default:
                    return RedirectToAction("Login");

            }
        }

        public IActionResult Register()
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("Email")))
                return RedirectToAction("Home");
            return View();
        }
                
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(User user)
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("Email")))
                return RedirectToAction("Home");

            IEnumerable<User> _user = db.tblUser;
            if (_user.Any(u => u.ContactNo == user.ContactNo))
                ModelState.AddModelError("ContactNo", "Contact Number is already taken");

            ModelState.Remove("Email");
            ModelState.Remove("Password");

            if(ModelState.IsValid)
            {
                TempData.Clear();
                TempData.Add("Fname", user.Fname.Trim());
                TempData.Add("Mname", user.Mname.Trim());
                TempData.Add("Lname", user.Lname.Trim());
                TempData.Add("DOB", user.DateOfBirth.ToString().Trim());
                TempData.Add("Gender", user.Gender.ToString().Trim());
                TempData.Add("ContactNo", user.ContactNo.ToString().Trim());

                return RedirectToAction("AddPassword", new
                {
                    id = 3,
                });
            }

            return View(user);
        }

        public IActionResult Logout()
        {
            HttpContext.Response.Cookies.Delete("Email");
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AddPassword(int? id)
        {
            // From forgot password
            if (id == 1)
            {
                HttpContext.Session.SetString("AddPasswordFlag", "1");
            }
            // From change password
            else if (id == 2)
            {
                HttpContext.Session.SetString("AddPasswordFlag", "2");

            }
            // From registration form
            else if (id == 3)
            {
                HttpContext.Session.SetString("AddPasswordFlag", "3");
            }
            // From nowhere
            else
            {
                HttpContext.Session.SetString("AddPasswordFlag", "0");
                return RedirectToAction("Register");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddPassword(Register register)
        {
            User user;
            int passFlag = Convert.ToInt32(HttpContext.Session.GetString("AddPasswordFlag"));
            // From forgot password
            if(passFlag == 1)
            {
                if (!db.tblUser.Any(user => user.Email == register.Email))
                {
                    ModelState.AddModelError("Email", "The user associated with this email address doesn't exists");
                }
            }
            // From change password
            else if (passFlag == 2)
            {
                ModelState.Remove("Email");
            }
            // From registration
            else if (passFlag == 3)
            {
                if(db.tblUser.Any(user => user.Email == register.Email))
                {
                    ModelState.AddModelError("Emai", "User associated with this email address alreasy exists");
                }
            }
            else
            {
                return RedirectToAction("Registration");
            }

            if (Convert.ToInt32(register.Otp) == otp)
            {
                if (register.Password != register.RePassword)
                {
                    ModelState.AddModelError("Password", "The passwords do not match");
                }

                if(ModelState.IsValid)
                {
                    if(passFlag == 1)
                    {
                        user = db.tblUser.First(u => u.Email == register.Email);
                        user.Password = register.Password;
                        db.SaveChanges();

Suffer Travels/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Safar Travels</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/theme4.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Suffer_Travels.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="icon" href="~/travel.png" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-dark bg-primary border-bottom box-shadow py-3 py-lg-3">
            <div class="container container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Safar Travels</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="Login">Log in</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-white" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-white" asp-area="" asp-controller="Chart" asp-action="Index">ChartJSTesting</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    @RenderBody()

    <footer class="border-top footer text-muted">

        <div class="container">
            <a asp-controller="User" asp-action="RegisterPartner" class="link-primary">Register as partner</a>
        </div>
        <div class="container">
            &copy; 2022 - Suffer Travels - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        <div class="container">
            <partial name="_Notification" />
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>*@
    <script src="~/lib/popperjs/core/dist/umd/popper.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Suffer Travels/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
	</script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script type="text/javascript">
        toastr.error('@TempData["error"]');
	</script>
}